/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package core.view;

import core.controller.AdditionController;
import core.controller.DivisionController;
import core.controller.IOperationController;
import core.controller.MultiplicationController;
import core.controller.PowerController;
import core.controller.SubstractionController;
import core.controllers.utils.Response;
import core.model.Addition;
import core.model.Division;
import core.model.IOperation;
import core.model.Multiplication;
import core.model.Power;
import core.model.Substraction;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import core.model.storage.History;

/**
 *
 * @author edangulo
 */
public class CalculatorFrame extends javax.swing.JFrame {

    private History history;

    /**
     * Creates new form Calculator
     */
    public CalculatorFrame() {

        this.history = History.getInstance();
        IOperationController controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        subsButton = new javax.swing.JButton();
        multButton = new javax.swing.JButton();
        divButton = new javax.swing.JButton();
        potButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        updtButton = new javax.swing.JButton();
        num1Field = new javax.swing.JTextField();
        num2Field = new javax.swing.JTextField();
        num1Label = new javax.swing.JLabel();
        num2Label = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        historyScroll = new javax.swing.JScrollPane();
        historyDisplay = new javax.swing.JList<>();
        resultField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleLabel.setText("Calculator");

        addButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        subsButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        subsButton.setText("Subtract");
        subsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subsButtonActionPerformed(evt);
            }
        });

        multButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        multButton.setText("Multiply");
        multButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multButtonActionPerformed(evt);
            }
        });

        divButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        divButton.setText("Divide");
        divButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divButtonActionPerformed(evt);
            }
        });

        potButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        potButton.setText("Potency");
        potButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        clearButton.setText("Clear numbers");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        updtButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        updtButton.setText("Update history");
        updtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtButtonActionPerformed(evt);
            }
        });

        num1Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        num2Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        num1Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        num1Label.setText("Number 1");

        num2Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        num2Label.setText("Number 2");

        resultLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        resultLabel.setText("Result");

        historyDisplay.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        historyDisplay.setEnabled(false);
        historyScroll.setViewportView(historyDisplay);

        resultField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        resultField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        resultField.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(resultLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(num1Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(num2Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(num1Field)
                            .addComponent(num2Field)
                            .addComponent(resultField, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(potButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(multButton, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(subsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(divButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updtButton, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(historyScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num1Label)
                    .addComponent(num1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updtButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num2Label)
                            .addComponent(num2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resultLabel)
                            .addComponent(resultField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton)
                            .addComponent(subsButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(divButton)
                            .addComponent(multButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(potButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButton))
                    .addComponent(historyScroll))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

        AdditionController controller = new AdditionController(new Addition(), history);
        Response response = controller.calculate(num1Field.getText(), num2Field.getText());
        resultField.setText("");

        if (response.getStatus() >= 500) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.ERROR_MESSAGE);
        } else if (response.getStatus() >= 400) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Response Message", JOptionPane.INFORMATION_MESSAGE);
            String result = history.getOperations().get(history.getOperations().size() - 1).split("=")[1];
            resultField.setText("" + result);
        }


    }//GEN-LAST:event_addButtonActionPerformed

    private void subsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subsButtonActionPerformed

        SubstractionController controller = new SubstractionController(new Substraction(), history);
        Response response = controller.calculate(num1Field.getText(), num2Field.getText());
        resultField.setText("");

        if (response.getStatus() >= 500) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.ERROR_MESSAGE);
        } else if (response.getStatus() >= 400) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Response Message", JOptionPane.INFORMATION_MESSAGE);
            String result = history.getOperations().get(history.getOperations().size() - 1).split("=")[1];
            resultField.setText("" + result);
        }

    }//GEN-LAST:event_subsButtonActionPerformed

    private void multButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multButtonActionPerformed
        MultiplicationController controller = new MultiplicationController(new Multiplication(), history);
        Response response = controller.calculate(num1Field.getText(), num2Field.getText());
        resultField.setText("");

        if (response.getStatus() >= 500) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.ERROR_MESSAGE);
        } else if (response.getStatus() >= 400) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Response Message", JOptionPane.INFORMATION_MESSAGE);
            String result = history.getOperations().get(history.getOperations().size() - 1).split("=")[1];
            resultField.setText("" + result);

        }

    }//GEN-LAST:event_multButtonActionPerformed

    private void divButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divButtonActionPerformed

        DivisionController controller = new DivisionController(new Division(), history);
        Response response = controller.calculate(num1Field.getText(), num2Field.getText());
        resultField.setText("");

        if (response.getStatus() >= 500) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.ERROR_MESSAGE);
        } else if (response.getStatus() >= 400) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Response Message", JOptionPane.INFORMATION_MESSAGE);
            String result = history.getOperations().get(history.getOperations().size() - 1).split("=")[1];
            resultField.setText("" + result);

        }
    }//GEN-LAST:event_divButtonActionPerformed

    private void potButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potButtonActionPerformed
        PowerController controller = new PowerController(new Power(), history);
        Response response = controller.calculate(num1Field.getText(), num2Field.getText());
        resultField.setText("");
        if (response.getStatus() >= 500) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.ERROR_MESSAGE);
        } else if (response.getStatus() >= 400) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Response Message", JOptionPane.INFORMATION_MESSAGE);
            String result = response.getObject().toString();
            resultField.setText("" + result);

        }

    }//GEN-LAST:event_potButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        num1Field.setText("");
        num2Field.setText("");
        resultField.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void updtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtButtonActionPerformed

        DefaultListModel model = new DefaultListModel();
        ArrayList<String> operaciones = this.history.getOperations();
        Collections.reverse(operaciones);
        model.addAll(operaciones);
        historyDisplay.setModel(model);
        Collections.reverse(operaciones);

    }//GEN-LAST:event_updtButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton divButton;
    private javax.swing.JList<String> historyDisplay;
    private javax.swing.JScrollPane historyScroll;
    private javax.swing.JButton multButton;
    private javax.swing.JTextField num1Field;
    private javax.swing.JLabel num1Label;
    private javax.swing.JTextField num2Field;
    private javax.swing.JLabel num2Label;
    private javax.swing.JButton potButton;
    private javax.swing.JTextField resultField;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JButton subsButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton updtButton;
    // End of variables declaration//GEN-END:variables
}
